/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void button1_click1(GButton source, GEvent event) { //_CODE_:button1:313796:
  println("button1 - GButton >> GEvent." + event + " @ " + millis());
  arduino.digitalWrite(9, Arduino.HIGH);
  delay(1000);
} //_CODE_:button1:313796:

public void button2_click1(GButton source, GEvent event) { //_CODE_:button2:841541:
  println("button2 - GButton >> GEvent." + event + " @ " + millis());
  arduino.digitalWrite(9, Arduino.LOW);
  delay(1000);
} //_CODE_:button2:841541:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  surface.setTitle("Sketch Window");
  button1 = new GButton(this, 110, 150, 80, 30);
  button1.setText("Light ON!");
  button1.setTextBold();
  button1.setTextItalic();
  button1.addEventHandler(this, "button1_click1");
  button2 = new GButton(this, 240, 150, 80, 30);
  button2.setText("Light OFF!");
  button2.setTextBold();
  button2.setTextItalic();
  button2.addEventHandler(this, "button2_click1");
}

// Variable declarations 
// autogenerated do not edit
GButton button1; 
GButton button2; 